os:
- linux
- osx
# Will visit windows once build / test env issues have been figured out for
# that platform.
# - windows

language: go

go:
- "1.12"

env:
- GO111MODULE=on

script:
- make test
- make e2e

notifications:
  email: false
